import type { TaxonomyDefinition } from "./types";

const TERMS = [
  "Agriculture and Food",
  "Animals",
  "Armed Forces and National Security",
  "Arts, Culture, Religion",
  "Civil Rights and Liberties, Minority Issues",
  "Commerce",
  "Congress",
  "Crime and Law Enforcement",
  "Economics and Public Finance",
  "Education",
  "Emergency Management",
  "Energy",
  "Environmental Protection",
  "Families",
  "Finance and Financial Sector",
  "Foreign Trade and International Finance",
  "Government Operations and Politics",
  "Health",
  "Housing and Community Development",
  "Immigration",
  "International Affairs",
  "Labor and Employment",
  "Law",
  "Native Americans",
  "Public Lands and Natural Resources",
  "Science, Technology, Communications",
  "Social Sciences and History",
  "Social Welfare",
  "Sports and Recreation",
  "Taxation",
  "Transportation and Public Works",
  "Water Resources Development",
] as const;

const GROUPS = [
  {
    label: "Rights & Justice",
    colorClasses: "bg-purple-100 text-purple-700 border border-purple-200",
    terms: [
      "Civil Rights and Liberties, Minority Issues",
      "Crime and Law Enforcement",
      "Law",
      "Native Americans",
      "Immigration",
    ],
  },
  {
    label: "Health & Welfare",
    colorClasses: "bg-rose-100 text-rose-700 border border-rose-200",
    terms: ["Health", "Social Welfare", "Families", "Social Sciences and History"],
  },
  {
    label: "Economy",
    colorClasses: "bg-emerald-100 text-emerald-700 border border-emerald-200",
    terms: [
      "Economics and Public Finance",
      "Finance and Financial Sector",
      "Commerce",
      "Foreign Trade and International Finance",
      "Taxation",
      "Labor and Employment",
    ],
  },
  {
    label: "Environment & Land",
    colorClasses: "bg-green-100 text-green-700 border border-green-200",
    terms: [
      "Environmental Protection",
      "Public Lands and Natural Resources",
      "Water Resources Development",
      "Animals",
      "Agriculture and Food",
    ],
  },
  {
    label: "Infrastructure & Energy",
    colorClasses: "bg-amber-100 text-amber-800 border border-amber-200",
    terms: [
      "Transportation and Public Works",
      "Energy",
      "Housing and Community Development",
    ],
  },
  {
    label: "Defense & Foreign",
    colorClasses: "bg-slate-100 text-slate-700 border border-slate-200",
    terms: [
      "Armed Forces and National Security",
      "International Affairs",
      "Emergency Management",
    ],
  },
  {
    label: "Knowledge & Culture",
    colorClasses: "bg-cyan-100 text-cyan-700 border border-cyan-200",
    terms: [
      "Education",
      "Science, Technology, Communications",
      "Arts, Culture, Religion",
      "Sports and Recreation",
    ],
  },
  {
    label: "Government",
    colorClasses: "bg-blue-100 text-blue-700 border border-blue-200",
    terms: ["Government Operations and Politics", "Congress"],
  },
] as const;

// Pinned subset for compact UI surfaces (Bills "Desks" pills, sidebars).
// TODO: future iteration could derive these from a BillView-weighted query
// (engagement signal already collected in prisma/schema.prisma BillView model).
const PRIORITIZED_TERMS = [
  "Health",
  "Economics and Public Finance",
  "Civil Rights and Liberties, Minority Issues",
  "Immigration",
  "Environmental Protection",
  "Crime and Law Enforcement",
] as const;

// Lowercase free-form → canonical LoC value.
// Covers (a) the legacy 12-tag vocab from the deleted lib/topics.ts, and
// (b) the lowercase free-form strings the org seed file used.
const ALIASES: Record<string, string> = {
  // Legacy 12-tag vocab
  healthcare: "Health",
  economy: "Economics and Public Finance",
  environment: "Environmental Protection",
  education: "Education",
  immigration: "Immigration",
  defense: "Armed Forces and National Security",
  infrastructure: "Transportation and Public Works",
  "civil rights": "Civil Rights and Liberties, Minority Issues",
  technology: "Science, Technology, Communications",
  housing: "Housing and Community Development",
  agriculture: "Agriculture and Food",
  "foreign policy": "International Affairs",
  // Org seed free-form strings
  "voting rights": "Civil Rights and Liberties, Minority Issues",
  "criminal justice": "Crime and Law Enforcement",
  privacy: "Civil Rights and Liberties, Minority Issues",
  climate: "Environmental Protection",
  energy: "Energy",
  "public lands": "Public Lands and Natural Resources",
  elections: "Government Operations and Politics",
  democracy: "Government Operations and Politics",
  "civic engagement": "Government Operations and Politics",
  "gun safety": "Crime and Law Enforcement",
  "public safety": "Crime and Law Enforcement",
  "reproductive rights": "Health",
  "women's health": "Health",
  labor: "Labor and Employment",
  "food security": "Social Welfare",
  poverty: "Social Welfare",
  "social services": "Social Welfare",
  "disability rights": "Civil Rights and Liberties, Minority Issues",
  "consumer protection": "Commerce",
  "financial regulation": "Finance and Financial Sector",
};

const KEYWORD_RULES = [
  { term: "Health", keywords: ["health", "medicare", "medicaid", "drug", "hospital", "medical", "insurance", "mental health", "vaccine", "fda"] },
  { term: "Taxation", keywords: ["tax", "taxation", "irs", "revenue", "tariff"] },
  { term: "Economics and Public Finance", keywords: ["budget", "fiscal", "debt ceiling", "spending", "deficit", "appropriation", "appropriations"] },
  { term: "Environmental Protection", keywords: ["climate", "environment", "emission", "clean air", "clean water", "pollution", "carbon", "epa", "conservation"] },
  { term: "Energy", keywords: ["energy", "oil", "gasoline", "solar", "renewable", "nuclear", "fossil fuel", "pipeline", "drilling"] },
  { term: "Education", keywords: ["education", "school", "student", "college", "university", "k-12", "teacher"] },
  { term: "Immigration", keywords: ["immigration", "border", "asylum", "visa", "citizenship", "migrant", "refugee", "daca"] },
  { term: "Armed Forces and National Security", keywords: ["defense", "military", "army", "navy", "air force", "marines", "national security", "troops", "pentagon"] },
  { term: "Transportation and Public Works", keywords: ["highway", "bridge", "transit", "airport", "rail", "ports", "infrastructure"] },
  { term: "Civil Rights and Liberties, Minority Issues", keywords: ["civil rights", "discrimination", "voting rights", "lgbtq", "minority", "equal protection"] },
  { term: "Science, Technology, Communications", keywords: ["technology", "cyber", "artificial intelligence", "internet", "broadband", "telecom", "spectrum", "data privacy"] },
  { term: "Housing and Community Development", keywords: ["housing", "rent", "mortgage", "homeless", "affordable", "hud"] },
  { term: "Agriculture and Food", keywords: ["agriculture", "farm", "food", "crop", "rural", "livestock", "usda"] },
  { term: "International Affairs", keywords: ["foreign", "diplomatic", "treaty", "sanction", "international", "nato", "embassy", "ambassador"] },
  { term: "Crime and Law Enforcement", keywords: ["crime", "criminal", "gun", "firearm", "police", "sentencing", "prison", "fentanyl", "trafficking"] },
  { term: "Native Americans", keywords: ["tribal", "native american", "indian tribe", "indigenous", "bia"] },
  { term: "Water Resources Development", keywords: ["watershed", "drought", "river", "dam", "reservoir", "irrigation"] },
  { term: "Emergency Management", keywords: ["emergency", "disaster", "fema", "hurricane", "wildfire", "earthquake", "flood"] },
  { term: "Labor and Employment", keywords: ["labor", "workers", "union", "wages", "employment", "overtime", "minimum wage", "workplace"] },
  { term: "Finance and Financial Sector", keywords: ["bank", "lending", "securities", "sec ", "wall street", "credit"] },
  { term: "Foreign Trade and International Finance", keywords: ["trade agreement", "export", "import", "customs", "wto", "ustr"] },
  { term: "Commerce", keywords: ["antitrust", "consumer protection", "small business", "ftc"] },
  { term: "Animals", keywords: ["animal welfare", "wildlife", "endangered species", "pets"] },
  { term: "Public Lands and Natural Resources", keywords: ["national park", "national forest", "wilderness", "blm", "public lands"] },
  { term: "Arts, Culture, Religion", keywords: ["arts", "humanities", "museum", "religion", "religious"] },
  { term: "Social Welfare", keywords: ["welfare", "snap", "hunger", "poverty", "food stamp"] },
  { term: "Families", keywords: ["family leave", "child care", "foster care", "adoption", "marriage"] },
  { term: "Social Sciences and History", keywords: ["census", "statistics bureau", "national archive"] },
  { term: "Sports and Recreation", keywords: ["sports", "olympics", "athletes", "ncaa"] },
  { term: "Government Operations and Politics", keywords: ["campaign finance", "federal employees", "ethics", "elections", "ballot"] },
  { term: "Congress", keywords: ["congressional", "capitol police", "oversight subpoena"] },
  { term: "Law", keywords: ["supreme court", "judge", "judicial", "bankruptcy", "habeas"] },
] as const;

const IMAGE_QUERIES: Record<string, string[]> = {
  "Agriculture and Food": ["farm fields agriculture"],
  Animals: ["wildlife conservation animals"],
  "Armed Forces and National Security": ["military service members"],
  "Arts, Culture, Religion": ["museum gallery culture"],
  "Civil Rights and Liberties, Minority Issues": ["civil rights march protest"],
  Commerce: ["commerce business storefront"],
  Congress: ["united states capitol building"],
  "Crime and Law Enforcement": ["police officers patrol car"],
  "Economics and Public Finance": ["economy financial district"],
  Education: ["students classroom school"],
  "Emergency Management": ["emergency response disaster relief"],
  Energy: ["renewable energy power plant"],
  "Environmental Protection": ["environment conservation landscape"],
  Families: ["family parent child"],
  "Finance and Financial Sector": ["bank wall street finance"],
  "Foreign Trade and International Finance": ["shipping container port trade"],
  "Government Operations and Politics": ["government office washington"],
  Health: ["healthcare hospital medicine"],
  "Housing and Community Development": ["affordable housing apartment buildings"],
  Immigration: ["immigration passport border crossing"],
  "International Affairs": ["international diplomacy flags"],
  "Labor and Employment": ["workers labor union"],
  Law: ["courtroom gavel justice"],
  "Native Americans": ["native american tribal nation"],
  "Public Lands and Natural Resources": ["national park public lands"],
  "Science, Technology, Communications": ["technology data network"],
  "Social Sciences and History": ["library archive research"],
  "Social Welfare": ["food bank community assistance"],
  "Sports and Recreation": ["sports stadium athletes"],
  Taxation: ["tax forms paperwork"],
  "Transportation and Public Works": ["bridge infrastructure highway"],
  "Water Resources Development": ["water reservoir dam"],
};

export const LOC_POLICY_AREA: TaxonomyDefinition = {
  id: "loc-policy-area",
  displayName: "LoC Policy Area",
  terms: TERMS,
  groups: GROUPS,
  prioritizedTerms: PRIORITIZED_TERMS,
  aliases: ALIASES,
  keywordRules: KEYWORD_RULES,
  imageQueries: IMAGE_QUERIES,
};
