FROM public.ecr.aws/lambda/nodejs:20

WORKDIR ${LAMBDA_TASK_ROOT}

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
COPY lib ./lib
COPY aws ./aws

RUN npx prisma generate

CMD ["aws/lambda/ingest.handler"]
